import './globals.css'
import { KumaRegistry } from '@kuma-ui/next-plugin/registry'
import { Inter } from 'next/font/google'
import React from 'react'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<{
  children: React.ReactNode
}> = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  )
}
export default RootLayout
