import { clsx } from 'clsx'
import React from 'react'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<{
  children: React.ReactNode
}> = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={clsx('bg-bg-primary')}>{children}</body>
    </html>
  )
}

export default RootLayout
